config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :dashboard
  resources :roles
  resources :users
  resources :farms
  resources :maps do 
    collection do 
      get 'kml_viewer/:id' => 'maps#kml_viewer'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farm.rb
class Farm < ApplicationRecord
  mount_uploader :photo, FarmPhotoUploader
  has_many :users, through: :farm_users
  has_many :maps
  serialize :polygon
end

app/models/farm_user.rb
class FarmUser < ApplicationRecord
  belongs_to :farm, optional: true
  belongs_to :user, optional: true
end

app/models/map.rb
class Map < ApplicationRecord
  mount_uploader :file, MapFileUploader
  belongs_to :farm, optional: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role, optional: true
  has_one :user_detail
  has_many :farms, through: :farm_users
  accepts_nested_attributes_for :user_detail
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_index_path
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end

end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController


  def index
    @farms = Farm.all.order("id DESC")
  end

  def new
    @farm = Farm.new
  end

  def create
    farm = Farm.new(name: permit_params[:name], address: permit_params[:address], photo: permit_params[:photo], polygon: permit_params[:polygon].to_json)
    if farm.save
      FarmUser.create(farm_id: farm.id, user_id: params[:farm][:user_id])
      redirect_to farms_path 
    end
  end

  def edit
    @farm = Farm.find(params[:id])
  end

  def update
    farm = Farm.find(params[:id])
    if farm.update_attributes(permit_params)
      uf = FarmUser.find_by(farm_id: farm.id)
      uf.update_attributes(user_id: params[:farm][:user_id])
      redirect_to farms_path 
    end
  end

  def permit_params
    params.require(:farm).permit(:name, :address, :photo, :polygon)
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController


  def index
    @maps = Map.all.order("id DESC")
  end

  def new
    @map = Map.new
  end

  def create
    map = Map.new(permit_params)
    redirect_to maps_path if map.save
  end

  def edit
    @map = Map.find(params[:id])
  end

  def update
    map = Map.find(params[:id])
    redirect_to maps_path if map.update_attributes(permit_params)
  end

  def kml_viewer
    @map = Map.find(params[:id])
  end

  def permit_params
    params.require(:map).permit(:name, :description, :farm_id, :file)
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController


  def index
    @roles = Role.all.order("id DESC")
  end

  def new
    @role = Role.new
  end

  def create
    role = Role.new(permit_params)
    redirect_to roles_path if role.save
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
    role = Role.find(params[:id])
    redirect_to roles_path if role.update_attributes(permit_params)
  end

  def permit_params
    params.require(:role).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order("id DESC")
  end

  def new
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="row align-middle">
    <!-- 7 -->
    <div class="column large-12">
      <div class="col-md-6">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">Usuarios Registrados</h3>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="col-md-12">
                <canvas id="box_1" width="400" height="260"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">Fincas registradas</h3>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="col-md-12">
                <canvas id="box_2" width="400" height="260"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
      <script>
        var ctx = $('#box_1');

        labels = ["Activos", "Inactivos"] 
        data = [<%= User.count %>, 0]

        var myChart = new Chart(ctx, {
          type: 'pie',
          data: {
            labels: labels,
            datasets: [{
              label: 'Usuarios',
              data: data,
              backgroundColor: [
                '#6F42DD',
                '#FC6C6E',,
              ]
            }]
          },
          options: {
            legend: false,
            responsive: true,
            title: {
              display: false
            },
            scales: {
              xAxes: [{
                display: false
              }],
              yAxes: [{
                display: false,
              }]
            }
          }
        });
      </script>
      <script>
        var ctx = $('#box_2');
        labels = ["Activos", "No activos"]
        data = [<%= Farm.count %>,0]
        //VALIDAR FECHAS
        
        var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
            labels: labels,
            datasets: [{
              label: 'Terrenos',
              data: data,
              backgroundColor: '#fd9028',
              borderColor: '#28a5fd',
              pointBackgroundColor: '#28a5fd',
              borderWidth: 1
            }]
          },
          options: {
            legend: false,
            responsive: true,
            title: {
              display: false
            },
            scales: {
              xAxes: [{
                scaleLabel: {
                  display: true,
                  labelString: 'Meses'
                }
              }],
              yAxes: [{
                stacked: true,
                scaleLabel: {
                  display: true,
                  labelString: 'Terrenos'
                }
              }]
            }
          }
        });
      </script>
    </div>

app/views/farms/_form.html.erb
<div class="form-group">
  <%= f.input :name, label: false, input_html: { class: "form-control", placeholder: "Nombre de terreno" } %>
</div>
<div class="form-group">
  <%= f.input :address, label: false, input_html: { class: "form-control", placeholder: "Dirección de terreno" } %>
</div>
<div class="form-group">
  <%= f.input :photo, label: "Seleccione una foto", input_html: { class: "form-control"} %>
</div>

<div class="form-group">
  <%= select_tag "farm[user_id]", options_from_collection_for_select(User.all, "id", "email"), class: "form-control" %>
</div>



<div class="form-group">
  <%= f.input :polygon, as: :hidden %>
</div>



<div id="map" style="height: 400px;"></div>
<a class="btn btn-primary export">Exportar</a>
<br>
<br>

<script type="text/javascript">
  $(document).ready(function(){

    polygonValue = []

    map = new L.Map('map', { drawControl: true }).setView([13.7013266, -89.2244339],15);

    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // FeatureGroup is to store editable layers
     var drawnItems = new L.FeatureGroup();
     map.addLayer(drawnItems);
     var drawControl = new L.Control.Draw({
         edit: {
             featureGroup: drawnItems
         }
     });
     map.addControl(drawControl);

    var shapeOptions = {
          color: '#0066FF',
          fillColor: '#0066FF',
          // clickable: false
          weight: 10
    };

    var opt = {
        position: 'topright',
        draw: {
            polygon: {
                allowIntersection: false,
                drawError: {
                    color: '#FF0000',
                    message: ''
                },
                repeatMode: false,
                shapeOptions: shapeOptions
            }
        },
        edit: {
            featureGroup: drawnItems, //REQUIRED!!
            remove: false
        }
    };

    var editing = false;
    map.on('click', function(e) {
      lat = e.latlng.lat;
      long = e.latlng.lng;
      polygonValue.push([lat,long]);

      if(!editing){ // do not start multiple "edit sessions"
        editing = true;
        var polyEdit = new L.Draw.Polygon(map);
        polyEdit.enable();
        polyEdit.addVertex(e.latlng);
      }
    });

    map.on('draw:created', function (e) {
      console.log(polygonValue);
      $("#farm_polygon").val(polygonValue).text(polygonValue);
      editing = false;
      var type = e.layerType,
          layer = e.layer;
      drawnItems.addLayer(layer);
      console.log(drawnItems);
    });

    $(".export").on("click", function(e){
      kmlFileName = $("#farm_name").val();
      data = drawnItems.toGeoJSON();
      var kml = tokml(data);
      var convertedData = 'application/xml;charset=utf-8,' + encodeURIComponent(kml);
      $(this).attr('href', 'data:' + convertedData); 
      $(this).attr('download', '<%= @farm.name + Date.today.strftime("-%m-%d-%Y")%>.kml');
      //console.log("<%= @farm.name + Date.today.strftime("-%m-%d-%Y")%> + .kml")

      //var convertedData = 'text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(data));
      //var kml = tokml(convertedData);
      //console.log(encodeURIComponent(JSON.stringify(data)));
      //$(this).attr('href', 'data:' + kml);
      //$(this).attr('download', "mapa.kml");
    });

    
    
  });
</script>

app/views/farms/edit.html.erb
<section class="content-header">
  <h1>
    Terrenos<br>
    <small>Editar terreno: <b><%= @farm.name %></b></small>
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="box box-success">
      <%= simple_form_for @farm, url: farm_path do |f| %>
        <div class="box-body">
          <%= render partial: "form", locals: { f: f } %>
        </div>
        <div class="box-footer text-center">
          <%= link_to "Cancelar".html_safe, farms_path, class: "btn bg-navy"%>
          <%= f.submit "Actualizar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/farms/index.html.erb
<section class="content-header">
  <h1>
    Terrenos
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-header">
        <%= link_to "<i class='fa fa-plus'></i> Nuevo Terreno".html_safe,new_farm_path, class: "btn btn-success" %>
        <%= link_to "<i class='fa fa-back'></i> Ir a dashboard".html_safe, dashboard_index_path, class: "btn btn-info" %>
      </div>
      <hr>
      <div class="box-body">
        <% if @farms.size > 0 %>
        <div class="table-responsive">
          <table class="table table-hover" id="datatable">
            <thead>
              <tr>
                <th>Nombre</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @farms.each do |farm| %>
              <tr>
                <td><%=farm.name%></td>
                <td><%=farm.address%></td>
                <td>
                  <div class="btn-group">
                    <%= link_to "<i class='fa fa-eye'></i>".html_safe, farm.photo.url, target: "_blank", class: "btn btn-info", title: "Ver archivo" %>
                    <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_farm_path(farm), class: "btn btn-warning", title: "Editar" %>
                    <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_map_path, class: "btn btn-success", title: "Subir archivo mapa" %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
        <div class="callout callout-warning">
          <h4>Opps!</h4>
          <p>No se ha añadido ningún registro.</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#datatable").DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  });
</script>

app/views/farms/new.html.erb
<section class="content-header">
  <h1>
    Terrenos<br>
    <small>Crear terreno nuevo</small>
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="box box-success">
      <%= simple_form_for @farm, url: farms_path, method: :post do |f| %>
        <div class="box-body">
          <%= render partial: "form", locals: { f: f } %>
        </div>
        <div class="box-footer text-center">
          <%= link_to "Cancelar".html_safe, farms_path, class: "btn bg-navy"%>
          <%= f.submit "Crear", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agropymebh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
            integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
            crossorigin=""></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <%= javascript_include_tag 'leaflet-kml', :defer => "defer"%>
    <%= javascript_include_tag 'tokml', :defer => "defer"%>
  </head>

  <body>
    <% if current_user %>
        <nav class="navbar navbar-inverse" style="background-color: #191963">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/dashboard">Agropyme App BH</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><%= link_to "Roles", roles_path %></li>
                    <li><%= link_to "Usuarios", users_path %></li>
                    <li><%= link_to "Terrenos", farms_path %></li>
                    <li><%= link_to "Mapas", maps_path %></li>
                    <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
                </ul>
            </div>
        </nav>
    <%end%>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <%= yield %>
            </div>
        </div>
    </div>
  </body>
</html>

app/views/maps/_form.html.erb
<div class="form-group">
  <%= f.input :name, label: false, input_html: { class: "form-control", placeholder: "Nombre del mapa" } %>
</div>

<div class="form-group">
  <%= f.input :description, label: false, input_html: { class: "form-control", placeholder: "Agregra la información del archivo kml" } %>
</div>

<div class="form-group">
  <%= f.input :farm_id, collection: Farm.all.map{|x| [x.name, x.id]}, label: "Selecciona a que terreno pertenece", input_html: { class: "form-control"} %>
</div>

<div class="form-group">
  <%= f.input :file, label: false, input_html: { class: "form-control"} %>
</div>

app/views/maps/edit.html.erb
<section class="content-header">
  <h1>
    Mapas<br>
    <small>Editar mapa: <b><%= @map.name %></b></small>
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="box box-success">
      <%= simple_form_for @map, url: map_path do |f| %>
        <div class="box-body">
          <%= render partial: "form", locals: { f: f } %>
        </div>
        <div class="box-footer text-center">
          <%= link_to "Cancelar".html_safe, maps_path, class: "btn bg-navy"%>
          <%= f.submit "Actualizar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/maps/index.html.erb
<section class="content-header">
  <h1>
    Archivos de mapas
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-header">
        <%= link_to "<i class='fa fa-plus'></i> Nuevo Mapa".html_safe,new_map_path, class: "btn btn-success" %>
        <%= link_to "<i class='fa fa-back'></i> Ir a dashboard".html_safe, dashboard_index_path, class: "btn btn-info" %>
      </div>
      <hr>
      <div class="box-body">
        <% if @maps.size > 0 %>
        <div class="table-responsive">
          <table class="table table-hover" id="datatable">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Terreno al que pertenece</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @maps.each do |map| %>
              <tr>
                <td><%=map.name%></td>
                <td><%=map.description%></td>
                <td><%=map.farm.name%></td>
                <td>
                  <div class="btn-group">
                    <%= link_to "<i class='fa fa-eye'></i>".html_safe, "/maps/kml_viewer/#{map.id}", target: "_blank", class: "btn btn-info", title: "Ver archivo" %>
                    <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_map_path(map), class: "btn btn-warning", title: "Editar" %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
        <div class="callout callout-warning">
          <h4>Opps!</h4>
          <p>No se ha añadido ningún registro.</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#datatable").DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  });
</script>

app/views/roles/edit.html.erb
<section class="content-header">
  <h1>
    Roles<br>
    <small>Editar rol: <b><%= @role.name %></b></small>
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="box box-success">
      <%= simple_form_for @role, url: role_path do |f| %>
        <div class="box-body">
          <%= render partial: "form", locals: { f: f } %>
        </div>
        <div class="box-footer text-center">
          <%= link_to "Cancelar".html_safe, roles_path, class: "btn bg-navy"%>
          <%= f.submit "Actualizar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<section class="content-header">
  <h1>
    Roles
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-header">
        <%= link_to "<i class='fa fa-plus'></i> Nuevo Rol".html_safe,new_role_path, class: "btn btn-success" %>
        <%= link_to "<i class='fa fa-back'></i> Ir a dashboard".html_safe, dashboard_index_path, class: "btn btn-info" %>
      </div>
      <hr>
      <div class="box-body">
        <% if @roles.size > 0 %>
        <div class="table-responsive">
          <table class="table table-hover" id="datatable">
            <thead>
              <tr>
                <th>Nombre</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @roles.each do |role| %>
              <tr>
                <td><%=role.name%></td>
                <td>
                  <div class="btn-group">
                    <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_role_path(role), class: "btn btn-warning", title: "Editar" %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
        <div class="callout callout-warning">
          <h4>Opps!</h4>
          <p>No se ha añadido ningún registro.</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#datatable").DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  });
</script>

app/views/users/edit.html.erb
<section class="content-header">
  <h1>
    Usuarios
    <small>Editar usuario <%= @user.email %></small>
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="box box-success">
      <%= simple_form_for @user, url: user_path do |f| %>
        <div class="box-body">
          <%= render partial: "form", locals: { f: f } %>
        </div>
        <div class="box-footer text-center">
          <%= link_to "Cancelar".html_safe, users_path, class: "btn bg-navy"%>
          <%= f.submit "Actualizar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<section class="content-header">
  <h1>
    Usuarios
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-header">
        <%= link_to "<i class='fa fa-plus'></i> Nuevo Usuario".html_safe,new_user_registration_path, class: "btn btn-success" %>
        <%= link_to "<i class='fa fa-back'></i> Ir a dashboard".html_safe, dashboard_index_path, class: "btn btn-info" %>
      </div>
      <hr>
      <div class="box-body">
        <% if @users.size > 0 %>
        <div class="table-responsive">
          <table class="table table-hover" id="datatable">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Rol al que pertenecen</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%=user.email%></td>
                <td><%=user.role.name%></td>
                <td>
                  <div class="btn-group">
                    <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_user_path(user), class: "btn btn-warning", title: "Editar" %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
        <div class="callout callout-warning">
          <h4>Opps!</h4>
          <p>No se ha añadido ningún registro.</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#datatable").DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  });
</script>

app/views/users/new.html.erb
<section class="content-header">
  <h1>
    Usuario
    <small>Crear usuario nuevo</small>
  </h1>
</section>
<br><br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="box box-success">
      <%= simple_form_for @user, url: users_path, method: :post do |f| %>
        <div class="box-body">
          
          <h1>Datos de logueo</h1>
          <hr>

          <div class="form-group">
            <%= f.input :email, label: false, input_html: { class: "form-control", placeholder: "Escribe tu correo" } %>
          </div>

          <div class="form-group">
            <%= f.input :password, label: false, input_html: { class: "form-control", placeholder: "Escribe tu password" } %>
          </div>

          <div class="form-group">
            <%= f.input :password_confirmation, label: false, input_html: { class: "form-control", placeholder: "Confirma tu password" } %>
          </div>

          <div class="form-group">
            <%= f.input :role_id, collection: Role.all.map{|role| [role.name, role.id]}, label: false, prompt: "--Selecciona un rol--" %>
          </div>


          <h1>Datos personales</h1>
          <hr>

          <%= f.fields_for @user_detail do |ff| %>

            <div class="form-group">
              <%= ff.input :name, label: false, input_html: { class: "form-control", placeholder: "Nombre de usuario" } %>
            </div>

            <div class="form-group">
              <%= ff.input :last_name, label: false, input_html: { class: "form-control", placeholder: "Apellidos de usuario" } %>
            </div>

            <div class="form-group">
              <%= ff.input :address, label: false, input_html: { class: "form-control", placeholder: "Dirección" } %>
            </div>

            <div class="form-group">
              <%= ff.input :phone_number, label: false, input_html: { class: "form-control", placeholder: "Teléfono de contacto" } %>
            </div>

            <div class="form-group">
              <%= ff.input :customer_number, label: false, input_html: { class: "form-control", placeholder: "Número de cliente en banco" } %>
            </div>

            <div class="form-group">
              <%= ff.input :dui, label: false, input_html: { class: "form-control", placeholder: "DUI" } %>
            </div>

            <div class="form-group">
              <%= ff.input :nit, label: false, input_html: { class: "form-control", placeholder: "NIT" } %>
            </div>

            <div class="form-group">
              <%= ff.input :description, label: false, input_html: { class: "form-control", placeholder: "Información adicional" } %>
            </div>

          <%end%>





        </div>
        <div class="box-footer text-center">
          <%= link_to "Cancelar".html_safe, users_path, class: "btn bg-navy"%>
          <%= f.submit "Crear", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>